export const KEYBINDINGS = [
  { keys: ["j", "↓"], description: "Move Down", narrativeDescription: "Navigate Data Streams" },
  { keys: ["k", "↑"], description: "Move Up", narrativeDescription: "Navigate Data Streams" },
  {
    keys: ["h", "←"],
    description: "Go to Parent Directory",
    narrativeDescription: "Navigate Data Streams",
  },
  {
    keys: ["l", "→", "Enter"],
    description: "Enter Directory / View Archive",
    narrativeDescription: "Infiltrate Directory",
  },
  { keys: ["gg"], description: "Jump to Top", narrativeDescription: "Trace Data Stream (Top)" },
  {
    keys: ["G"],
    description: "Jump to Bottom",
    narrativeDescription: "Trace Data Stream (Bottom)",
  },
  { keys: ["J"], description: "Scroll Preview Down", narrativeDescription: "Scan Preview Down" },
  { keys: ["K"], description: "Scroll Preview Up", narrativeDescription: "Scan Preview Up" },
  { keys: ["a"], description: "Create File/Directory", narrativeDescription: "Construct Modules" },
  { keys: ["d"], description: "Delete Selected", narrativeDescription: "Purge Threats" },
  { keys: ["r"], description: "Rename Selected", narrativeDescription: "Forge Identity" },
  { keys: ["Tab"], description: "Show File Info Panel", narrativeDescription: "Access Metadata" },
  {
    keys: ["x"],
    description: "Cut Selected",
    narrativeDescription: "Extract Payloads",
  },
  {
    keys: ["y"],
    description:
      "Copy/Yank Selected — copies items into the clipboard (does NOT remove them); use x (Cut) to mark items for moving",
    narrativeDescription: "Duplicate Assets",
  },
  { keys: ["p"], description: "Paste", narrativeDescription: "Deploy Modules" },
  { keys: ["Y", "X"], description: "Clear Clipboard", narrativeDescription: "Wipe Clipboard" },
  { keys: ["Space"], description: "Toggle Selection", narrativeDescription: "Mark Targets" },
  { keys: ["Ctrl+A"], description: "Select All", narrativeDescription: "Acquire All Targets" },
  { keys: ["Ctrl+R"], description: "Invert Selection", narrativeDescription: "Invert Acquisition" },
  { keys: ["f"], description: "Filter Files", narrativeDescription: "Scan Signatures" },
  {
    keys: ["z"],
    description: "FZF Find (Recursive)",
    narrativeDescription: "Quantum Jump (Global)",
  },
  {
    keys: ["Z"],
    description: "Zoxide Jump (History)",
    narrativeDescription: "Neural Link (History)",
  },
  {
    keys: ["Esc"],
    description: "Clear Filter / Exit Mode",
    narrativeDescription: "Disengage Protocols",
  },
  { keys: [","], description: "Open Sort Menu", narrativeDescription: "Optimize Sort Protocols" },
  { keys: [",a"], description: "Sort: Alphabetical", narrativeDescription: "Sort: Alphabetical" },
  {
    keys: [",A"],
    description: "Sort: Alphabetical (Reverse)",
    narrativeDescription: "Sort: Alphabetical (Reverse)",
  },
  { keys: [",m"], description: "Sort: Modified Time", narrativeDescription: "Sort: Chronological" },
  { keys: [",s"], description: "Sort: Size", narrativeDescription: "Sort: By Payload Size" },
  { keys: [",e"], description: "Sort: Extension", narrativeDescription: "Sort: By Filetype" },
  { keys: [",n"], description: "Sort: Natural", narrativeDescription: "Sort: Natural Order" },
  { keys: [",l"], description: "Sort: Cycle Linemode", narrativeDescription: "Cycle Display Mode" },
  { keys: [",-"], description: "Sort: Clear Linemode", narrativeDescription: "Clear Display Mode" },
  { keys: ["gh"], description: "Goto Home (~)", narrativeDescription: "Navigate: Home Sector" },
  {
    keys: ["gc"],
    description: "Goto Config (~/.config)",
    narrativeDescription: "Navigate: Config Matrix",
  },
  { keys: ["gw"], description: "Goto Workspace", narrativeDescription: "Navigate: Workspace Grid" },
  { keys: ["gi"], description: "Goto Incoming", narrativeDescription: "Navigate: Incoming Stream" },
  { keys: ["gd"], description: "Goto Datastore", narrativeDescription: "Navigate: Datastore Core" },
  { keys: ["gt"], description: "Goto Tmp (/tmp)", narrativeDescription: "Navigate: Temp Buffer" },
  { keys: ["gr"], description: "Goto Root (/)", narrativeDescription: "Navigate: Root Labyrinth" },
  { keys: ["."], description: "Toggle Hidden Files", narrativeDescription: "Reveal Hidden Traces" },
];

export const META_KEYBINDINGS = [
  { keys: ["Alt+M"], description: "Quest Map", narrativeDescription: "Access Neural Map" },
  { keys: ["Alt+H"], description: "Show Hint", narrativeDescription: "Query Oracle" },
  { keys: ["Alt+?"], description: "Show Help", narrativeDescription: "Access Codex" },
  {
    keys: ["Alt+Shift+M"],
    description: "Toggle Sound",
    narrativeDescription: "Toggle Audio Subroutines",
  },
];
